import type { User, Event } from './types'

export const ADMIN_CREDENTIALS = { email: 'admin@smktest.com', password: 'admin123' }

export const INITIAL_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'Administrator',
    phone: '08100000000',
    email: 'admin@smktest.com',
    password: 'admin123',
    role: 'admin',
    verified: true,
  },
  {
    id: 'host-1',
    name: 'Rizky Pratama',
    phone: '08111111111',
    email: 'rizky@host.com',
    password: 'host123',
    role: 'host',
    verified: true,
  },
  {
    id: 'umkm-1',
    name: 'Siti Rahayu',
    phone: '08122222222',
    email: 'siti@umkm.com',
    password: 'umkm123',
    role: 'umkm',
    verified: true,
    businessName: 'Batik Nusantara Siti',
  },
]

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt-1',
    name: 'Bazaar Ramadan 2026',
    hostId: 'host-1',
    hostName: 'Rizky Pratama',
    phone: '08111111111',
    type: 'Bazaar',
    date: '2026-08-05',
    location: 'Monas, Jakarta Pusat',
    tentCount: 80,
    image: 'https://images.unsplash.com/photo-1472653431158-6364773b2a56?w=600&h=300&fit=crop&auto=format',
    status: 'active',
    description: 'Bazaar tahunan dengan ratusan UMKM pilihan dari seluruh Nusantara.',
  },
  {
    id: 'evt-2',
    name: 'Festival Kuliner Nusantara',
    hostId: 'host-1',
    hostName: 'Rizky Pratama',
    phone: '08111111111',
    type: 'Festival',
    date: '2026-08-12',
    location: 'Alun-Alun Bandung',
    tentCount: 120,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=300&fit=crop&auto=format',
    status: 'active',
    description: 'Festival kuliner terbesar di Bandung dengan sajian khas dari berbagai daerah.',
  },
  {
    id: 'evt-3',
    name: 'Pameran Produk Lokal Jabar',
    hostId: 'host-1',
    hostName: 'Rizky Pratama',
    phone: '08111111111',
    type: 'Pameran',
    date: '2026-08-20',
    location: 'Trans Studio, Bandung',
    tentCount: 60,
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=300&fit=crop&auto=format',
    status: 'active',
    description: 'Wadah bagi UMKM Jawa Barat untuk memperkenalkan produk unggulan.',
  },
  {
    id: 'evt-4',
    name: 'Expo Kerajinan Tangan 2026',
    hostId: 'host-1',
    hostName: 'Rizky Pratama',
    phone: '08111111111',
    type: 'Expo',
    date: '2026-09-01',
    location: 'GOR Ken Arok, Malang',
    tentCount: 45,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=300&fit=crop&auto=format',
    status: 'pending',
    description: 'Pameran kerajinan tangan UMKM lokal untuk pasar ekspor.',
  },
  {
    id: 'evt-5',
    name: 'Market Day UMKM Surabaya',
    hostId: 'host-1',
    hostName: 'Rizky Pratama',
    phone: '08111111111',
    type: 'Market Day',
    date: '2026-08-08',
    location: 'Taman Bungkul, Surabaya',
    tentCount: 35,
    image: 'https://images.unsplash.com/photo-1506869640319-fe1a24fd76dc?w=600&h=300&fit=crop&auto=format',
    status: 'active',
    description: 'Market Day mingguan khusus UMKM Surabaya.',
  },
]
